//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpnTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Client_Address = new HashSet<Client_Address>();
            this.Quotations = new HashSet<Quotation>();
        }
    
        public int client_id { get; set; }
        public string client_name { get; set; }
        public string client_contact_no { get; set; }
    
        public virtual ICollection<Client_Address> Client_Address { get; set; }
        public virtual ICollection<Quotation> Quotations { get; set; }
    }
}
