//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpnTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labour
    {
        public Labour()
        {
            this.Labour_SOW = new HashSet<Labour_SOW>();
        }
    
        public int lab_id { get; set; }
        public string lab_desc { get; set; }
        public Nullable<decimal> lab_rate { get; set; }
    
        public virtual ICollection<Labour_SOW> Labour_SOW { get; set; }
    }
}
