//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpnTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Material_SOW = new HashSet<Material_SOW>();
            this.Order_Item = new HashSet<Order_Item>();
        }
    
        public int mat_id { get; set; }
        public string mat_desc { get; set; }
        public Nullable<decimal> mat_cost_price { get; set; }
        public Nullable<decimal> mat_mu_price { get; set; }
    
        public virtual ICollection<Material_SOW> Material_SOW { get; set; }
        public virtual ICollection<Order_Item> Order_Item { get; set; }
    }
}
