//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpnTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rpnTestEntities : DbContext
    {
        public rpnTestEntities()
            : base("name=rpnTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Client_Address> Client_Address { get; set; }
        public virtual DbSet<Labour> Labours { get; set; }
        public virtual DbSet<Labour_SOW> Labour_SOW { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Material_SOW> Material_SOW { get; set; }
        public virtual DbSet<Order_Item> Order_Item { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<Quote_SOW> Quote_SOW { get; set; }
        public virtual DbSet<Scope_of_Work> Scope_of_Work { get; set; }
    }
}
