//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpnTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Item
    {
        public int order_item_id { get; set; }
        public Nullable<int> order_no { get; set; }
        public Nullable<int> mat_id { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Order Order { get; set; }
    }
}
