//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpnTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Item = new HashSet<Order_Item>();
        }
    
        public int order_no { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
    
        public virtual ICollection<Order_Item> Order_Item { get; set; }
    }
}
