//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rpnTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scope_of_Work
    {
        public Scope_of_Work()
        {
            this.Labour_SOW = new HashSet<Labour_SOW>();
            this.Material_SOW = new HashSet<Material_SOW>();
            this.Quote_SOW = new HashSet<Quote_SOW>();
        }
    
        public int sow_id { get; set; }
        public string sow_desc { get; set; }
    
        public virtual ICollection<Labour_SOW> Labour_SOW { get; set; }
        public virtual ICollection<Material_SOW> Material_SOW { get; set; }
        public virtual ICollection<Quote_SOW> Quote_SOW { get; set; }
    }
}
